environment: disaster-recovery
images:
  - name: my-welcome-python-app
    registry: acr
    imagePath: systexacr.azurecr.io/my-welcome-python-app
    tag: v3
    containerRuntime: docker
    locationType: local
    scan:
      customFlags: ''
      register: true
      hideBase: false
      notCompliesCmd: ''
      onDisallowed: ignore
      showNegligible: false