environment: production
images:
  - name: my-welcome-python-app
    registry: systexacr.azurecr.io
    tag: v3
    containerRuntime: docker
    locationType: local
    scan:
      enabled: true
      hideBase: false
      onDisallowed: ignore
      showNegligible: false
      customFlags: ""
      notCompliesCmd: ""
      register: true